#!/bin/bash
name=$(jq -r '.name' data.json); type=$(jq -r '.types[0].type.name' data.json); h=$(jq -r '.height' data.json); w=$(jq -r '.weight' data.json); echo "${name^} is of type ${type^}, weighs $(awk "BEGIN{print $w/10}")kg, and is $(awk "BEGIN{print $h/10}")m tall."
